force-app/main/default/objects/Anime__c/Anime__c.object-meta.xml
<CustomObject>
    <label>Anime</label>
    <nameField>
        <label>Anime Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Anime</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Anime_List__c/Anime_List__c.object-meta.xml
<CustomObject>
    <label>Anime List</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>AnimeList Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Anime Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Anime_List__c/fields/Anime__c.field-meta.xml
<CustomField>
    <fullName>Anime__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Anime</label>
    <referenceTo>Anime__c</referenceTo>
    <relationshipLabel>Anime Lists</relationshipLabel>
    <relationshipName>Anime_Lists1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Anime_List__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Anime_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AnimeController.cls
public with sharing class AnimeController {
    @AuraEnabled
    public static User getCurrentUser(){
        return [SELECT Id, Name FROM User WHERE Id=:UserInfo.getUserId()];
    }

    @AuraEnabled
    public static String addAnime(Id animeId){
        
        Id userId = getCurrentUser().Id;
        Anime_List__c animeList = new Anime_List__c(Anime__c=animeId, User__c=userId);

        insert animeList; 
        return (String)animeId;
    }

    @AuraEnabled
    public static Boolean hasAnime(Id animeId){
        Id userId = getCurrentUser().Id;
        List<Anime_List__c> isMatch = [SELECT Anime__c FROM Anime_List__c 
                                       WHERE Anime_List__c.User__c =:userId 
                                       AND Anime__c =:animeId];
        if(isMatch.size() > 0)
            return true;
        return false;
    }
    public void getAnimeList(){
        // Anime_List__c userAnimeList =  [SELECT Anime__c FROM Anime_List__c 
        // WHERE Anime_List__c.User__c =:userId];
        // Anime__c show = new Anime__c(Id=animeId);
        // current contact(anime.Id=Anime__c.id)?
        
        // Anime_List__c userAnimeList =  [SELECT Anime__c FROM Anime_List__c 
        //                                 WHERE Anime_List__c.User__c =:userId];

                                  
    }
}