force-app/main/default/objects/Anime__c/Anime__c.object-meta.xml
<CustomObject>
    <label>Anime</label>
    <nameField>
        <label>Anime Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Anime</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Anime__c/fields/Cover_Image__c.field-meta.xml
<CustomField>
    <fullName>Cover_Image__c</fullName>
    <label>Cover Image</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Anime_List__c/Anime_List__c.object-meta.xml
<CustomObject>
    <label>Anime List</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>AnimeList Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Anime Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Anime_List__c/fields/Anime__c.field-meta.xml
<CustomField>
    <fullName>Anime__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Anime</label>
    <referenceTo>Anime__c</referenceTo>
    <relationshipLabel>Anime Lists</relationshipLabel>
    <relationshipName>Anime_Lists1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Anime_List__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Anime_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AnimeListController.cls
public with sharing class AnimeListController {
    public AnimeListController() {

    }

    @AuraEnabled
    public static List<List<Anime__c>> getAnimeList(){
        Id currentUser = AnimeController.getCurrentUser().Id;

        List<Anime_List__c> animeList = [SELECT Anime__c, Anime__r.Cover_Image__c 
                                        FROM Anime_List__c 
                                        WHERE Anime_List__c.User__c=:currentUser];
        List<List<Anime__c>> multiDimensionalImagesList = chunkifyList(animeList, 3);
        return multiDimensionalImagesList;
    }

    @AuraEnabled
    public static List<List<Anime__c>> chunkifyList(List<Anime_List__c> SingleDimensionalList, Integer cols){
        Integer counter = 0;
        List<List<Anime__c>> chunked = new List<List<Anime__c>>();

        while(counter < cols){
            chunked.add(new List<Anime__c>());
            counter += 1;
        }

        for(Integer index = 0; index < SingleDimensionalList.size(); index++){
            chunked[Math.mod(index, cols)].add(new Anime__c(Id=SingleDimensionalList[index].Anime__c, 
                                                        Cover_Image__c=SingleDimensionalList[index].Anime__r.Cover_Image__c));
        }

        return chunked;
    }

    @AuraEnabled
    public static List<List<Anime__c>> chunkifyAnime(List<Anime__c> SingleDimensionalList, Integer cols){
        Integer counter = 0;
        List<List<Anime__c>> chunked = new List<List<Anime__c>>();

        while(counter < cols){
            chunked.add(new List<Anime__c>());
            counter += 1;
        }

        for(Integer index = 0; index < SingleDimensionalList.size(); index++){
            chunked[Math.mod(index, cols)].add(SingleDimensionalList[index]);
        }

        return chunked;
    }

    @AuraEnabled
    public static List<List<Anime__c>> getFeaturedAnime(){
        // get featured anime
        List<Anime__c> featured = [SELECT Id, Anime__c.Cover_Image__c FROM Anime__c WHERE Is_Featured__c=true];

        List<List<Anime__c>> multiDimensionalImagesList = chunkifyAnime(featured, 3);
        return multiDimensionalImagesList;      
    }
}